Allow user to change music in menu
coop-deluxe/sm64coopdx pull request #212
Opened 2024-07-14 22:44 UTC by EmeraldLoc

The word "Music" does need translation, since it's 1 word, should I just use google translate?

I tried to make it as simple as it can be to add/remove songs to the main menu. All you have to do is edit the `gMainMenuSounds`, everything else is done for you.

`gMainMenuSounds` is a structure of a new type, `MainMenuSounds`, which contains a name, and a sound. `configMenuSounds` was changed to a `int`, and it now references an entry in the `gMainMenuSounds` table. The stuff done in `level_update.c` is very self explanatory. Stage music is handled with a custom definition, `STAGE_MUSIC`, that's set to the integer `0`. This is also passed into `gMainMenuSounds`. Something very important is that the stage music entry needs to ALWAYS be last in the table, this will be discussed later in this message. The main part I'm not super happy with is getting staff roll integration to work. When staff roll is toggled, I chose, as I don't know of any other methods, to recreate the panel. The reason is that the selection box's selection needs to be updated, and whether or not `Stage Music` exists needs to be updated as well.

2024-07-15 01:36 UTC, Cooliokid956 commented
> The word "Music" does need translation, since it's 1 word, should I just use google translate?

The word "Music" is available in `[SOUND]:MUSIC_VOLUME`, use the power of context clues to find the word "Music" in some of the trickier translations!

2024-07-19 09:11 UTC, Flower35 commented
> > The word "Music" does need translation, since it's 1 word, should I just use google translate?
> 
> The word "Music" is available in `[SOUND]:MUSIC_VOLUME`, use the power of context clues to find the word "Music" in some of the trickier translations!

Sorry, that's actually a terrible advice 😃

Quoting Wikipedia:

> In linguistics, declension (verb: to decline) is the changing of the form of a word, generally to express its syntactic function in the sentence, by way of some inflection.
 
> Unlike English, many languages use suffixes to specify subjects and objects and word cases in general.

---

And an example from `Polish.ini`:
```
MUSIC_VOLUME = "Głośność Muzyki"
```
* (Genitive Case - Dopełniacz): _„Muzyki”_

Here, _„Głośność Muzyki”_ literally (and naturally) translates as _"Volume of the Music"_

---

For "Music" as a single noun, the correct translation will be:
```
MUSIC = "Muzyka"
```
* (Nominative Case - Mianownik): _„Muzyka”_

---

Similarly for `Czech.ini` (`MUSIC = "písnička"`) and `Russian.ini` (`MUSIC = "музыка"`), although it would be nice if some native speaker / translator could verify these. 🙂

2024-07-19 09:15 UTC, Flower35 requested changes

2024-07-19 09:15 UTC, Flower35 commented on lang/Polish.ini
> +MUSIC = "Muzyki"
```suggestion
MUSIC = "Muzyka"
```

2024-07-19 09:15 UTC, Flower35 commented on lang/Russian.ini
> +MUSIC = "музыки"
```suggestion
MUSIC = "Музыка"
```

2024-07-19 09:15 UTC, Flower35 commented on lang/Czech.ini
> +MUSIC = "Hlasitost"
```suggestion
MUSIC = "Písnička"
```

2024-07-19 14:21 UTC, EmeraldLoc commented on lang/Polish.ini
> +MUSIC = "Muzyki"
Thank you!

2024-09-01 16:50 UTC, AgentXLP commented
> The word "Music" is available in `[SOUND]:MUSIC_VOLUME`, use the power of context clues to find the word "Music" in some of the trickier translations!

Lol

2024-09-01 17:15 UTC, merged

2024-09-03 05:27 UTC, frog8412 commented
> > > The word "Music" does need translation, since it's 1 word, should I just use google translate?
> > 
> > 
> > The word "Music" is available in `[SOUND]:MUSIC_VOLUME`, use the power of context clues to find the word "Music" in some of the trickier translations!
> 
> Sorry, that's actually a terrible advice 😃
> 
> Quoting Wikipedia:
> 
> > In linguistics, declension (verb: to decline) is the changing of the form of a word, generally to express its syntactic function in the sentence, by way of some inflection.
> 
> > Unlike English, many languages use suffixes to specify subjects and objects and word cases in general.
> 
> And an example from `Polish.ini`:
> 
> ```
> MUSIC_VOLUME = "Głośność Muzyki"
> ```
> 
> * (Genitive Case - Dopełniacz): _„Muzyki”_
> 
> Here, _„Głośność Muzyki”_ literally (and naturally) translates as _"Volume of the Music"_
> 
> For "Music" as a single noun, the correct translation will be:
> 
> ```
> MUSIC = "Muzyka"
> ```
> 
> * (Nominative Case - Mianownik): _„Muzyka”_
> 
> Similarly for `Czech.ini` (`MUSIC = "písnička"`) and `Russian.ini` (`MUSIC = "музыка"`), although it would be nice if some native speaker / translator could verify these. 🙂

Yep, this is correct, I'm a native Russian speaker and that is also the same in Russian (громкость музыки - музыка)