Implemented smlua_text_utils_dialog_get
coop-deluxe/sm64coopdx pull request #321
Opened 2024-09-15 06:11 UTC by EliteMasterEric

- Implemented `smlua_text_utils_dialog_get` as a new Lua API function.
  - This function returns a table providing the information for a given line of dialog.
  - This allows for mods to create custom dialog interfaces, and for mods to perform inline replacements on the text of existing dialog (for example, replacing one name with another)
- Added a hard-coded limit of 1024 characters to `smlua_text_utils_dialog_replace`.
  - This should not conflict with the vanilla game, as the longest dialog is the Lakitu roughly 780 characters.
- Added a Lua log warning to `smlua_text_utils_dialog_replace` which displays if the provided string exceeds the hard-coded length limit of `1024`.
- Added a Lua log warning to `smlua_text_utils_dialog_replace` which displays if the target dialog ID is invalid (outside the range of 1-170).

2024-09-15 06:28 UTC, Squishy6094 approved these changes
The madman picked up C and Lua did it in 2 hours,, I plan on implementing this in Character Select for replacing dialog from "Mario" to your current character.

2024-09-19 00:37 UTC, Isaac0-dev requested changes
Limiting the dialog length may cause mod incompatibilities if a mod has a massive string.
I feel like it'd be best to use autogen instead of manually creating `smlua_func_smlua_text_utils_dialog_get`.
This would require exposing the struct `DialogEntry`, and allowing cobjects to handle strings.

2024-09-19 00:37 UTC, Isaac0-dev commented on src/pc/lua/utils/smlua_text_utils.h
> +void convert_string_sm64_to_ascii(char *strAscii, const u8 *str64);
`convert_string_sm64_to_ascii` does not belong to `smlua_text_utils.c`
it is defined in `level_info.c`

2024-09-19 01:39 UTC, EliteMasterEric commented on src/pc/lua/utils/smlua_text_utils.h
> +void convert_string_sm64_to_ascii(char *strAscii, const u8 *str64);
I can correct this 👍

2024-09-19 07:47 UTC, EliteMasterEric commented
> Limiting the dialog length may cause mod incompatibilities if a mod has a massive string.

The reason I limited dialogue length is because I had to convert the internal dialog string into a `char*` that could be passed to Lua; this requires using `convert_string_sm64_to_ascii`, which requires a fixed length buffer.

> I feel like it'd be best to use autogen instead of manually creating `smlua_func_smlua_text_utils_dialog_get`. This would require exposing the struct `DialogEntry`, and allowing cobjects to handle strings.

I previously used autogen and then switched to manual in order to return a table containing all the values. I am new to Lua C and do not know how to expose a struct or allow cobjects to handle the strings being passed to Lua

2024-11-26 01:59 UTC, Isaac0-dev commented
Please feel free to reopen this pull request when you have implemented the requested changes.

2024-11-26 01:59 UTC, closed without merging