Update math_util.c and math_util.h to support autodoc with trig functions (inline instead of macros) and add new functions to smlua_math_utils
coop-deluxe/sm64coopdx pull request #359
Opened 2024-10-10 00:17 UTC by Multi-Volt

Hello,

This pull request continues the work from my previous PR, which can be found [here](https://github.com/coop-deluxe/sm64coopdx/pull/345#event-14580671499). The original repository was unintentionally deleted due to complications with format.sh, necessitating this re-implementation. In this update, I have replaced several macros in `math_util.h` with inline functions, which provide a slight [runtime efficiency improvement](https://en.wikipedia.org/wiki/Inline_expansion). Inline functions also offer enhanced type safety compared to macros, and I have introduced additional macros to support multiple data types, minimizing the need for any kind of overloading.

This PR also introduces new functions in `smlua_math_utils.c`, aimed at assisting modders with various calculations. The existing, unused functions in `misc.c` relating to angle conversions have been added here so modders can leverage the Lua math library's trigonometric functions when needed. Based on feedback from a recent poll on the Discord server, I added numerical conversions to support working in degrees as well, which was the majority's preferred format. Additionally, I implemented a basic function for computing the hypotenuse of two points, incorporating a variant of the fast square root algorithm (from Quake). These features are similar to ones already present in [SRB2's Lua implementation](https://wiki.srb2.org/wiki/Lua/Functions).

Poll:
![image](https://github.com/user-attachments/assets/a7718ed5-778a-4c1e-89c8-374380688ef3)

Example of performance increase (extreme case):

Before inlining:
![Screenshot from 2024-10-09 14-48-31](https://github.com/user-attachments/assets/4c5b2916-b27f-4324-bec5-3ced40260174)

After inlining:
![Screenshot from 2024-10-09 14-48-00](https://github.com/user-attachments/assets/5523817c-d6ad-4bda-af20-7c7ffdffb10f)

Please let me know if any further adjustments or formatting changes are needed.

2024-10-10 01:30 UTC, Isaac0-dev reviewed
The performance increase looks fairly significant. 
Most of the changes to `misc.c` are formatting changes, and some make the code more difficult to read than before imo.

2024-10-10 02:12 UTC, Multi-Volt commented
> The performance increase looks fairly significant. Most of the changes to `misc.c` are formatting changes, and some make the code more difficult to read than before imo.

Yeah that's mostly just a remnant from `format.sh`, I went ahead and reverted the formatting minus the removal of the functions now present in `smlua_math_utils`

2024-10-10 15:24 UTC, Multi-Volt commented
> > The performance increase looks fairly significant. Most of the changes to `misc.c` are formatting changes, and some make the code more difficult to read than before imo.
> 
> Yeah that's mostly just a remnant from `format.sh`, I went ahead and reverted the formatting minus the removal of the functions now present in `smlua_math_utils`.

Update: I have went ahead and taken the liberty to revert all changes made by `format.sh`, This should make the changes easier to review.

2024-10-14 00:24 UTC, Multi-Volt commented
Update 2: Added even more optimized versions of each function for even more performance gains by utilizing the builtins from GCC/Clang when they are available.

2024-10-17 08:24 UTC, Isaac0-dev requested changes
sorry I missed this before

2024-10-17 08:24 UTC, Isaac0-dev commented on src/pc/lua/utils/smlua_math_utils.c
> +s16 degrees_to_sm64(f32 degrees_angle) {
please use camelCase for the variable names here

2024-10-18 01:16 UTC, Multi-Volt commented on src/pc/lua/utils/smlua_math_utils.c
> +s16 degrees_to_sm64(f32 degrees_angle) {
went ahead and fixed the variable names adding camel case.

2024-10-18 02:20 UTC, merged